apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-key-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: random-key-app
  template:
    metadata:
      labels:
        app: random-key-app
    spec:
      containers:
      - name: random-key
        image: docker.io/haydter/random-key:latest
        args: ["1234"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1234
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1234
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: random-key-service
spec:
  type: LoadBalancer
  selector:
    app: random-key-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1234

